json

파일 읽기

In [29]:
f = open('Numbers.txt', 'r', encoding='utf8') # r, w 읽을때는 한방향만 선호, encoding='cp949'
#f.read() #f.read(5) 바이너리
f.readline().rstrip() # 한번 읽고 나면 다시 못 읽는다 -> 버퍼에서 가져오기 때문인가? 확인하기!
f.close()

In [23]:
with open('Numbers.txt', 'r') as f: # 매번 close해줘야 하는것 때문에 with문 사용하기! -> with문?
    print(f.readlines())

['hello world\n', 'welcom!']

In [ ]:
with open('Numbers.txt', 'r') as f:
    for line in f: # IObase가 최고 조상
        print(line.rstrip()) # 한 줄씩 읽어오고 있다!

hello world
welcom!

In [ ]:
with open('Numbers.txt', 'r') as f:
    for line in f: # IObase가 최고 조상
        print(line.rstrip()) # 한 줄씩 읽어오고 있다!

파일 쓰기

In [59]:
file = open('Numbers.txt', 'w')
file.write('1\n')
file.write('2\n')
#file.close()

2

In [61]:
answer = ['1','2','3']
content = '\n'.join(answer)
file.write(content)
file.flush() # flush -> close
file.close()

In [51]:
with open('Numbers2.txt', 'w') as file2:
    answer = ['1','2','3']
    content = '\n'.join(answer)
    file2.write(content)

In [52]:
with open('Numbers22.txt', 'w') as f:
    f.writelines(['1','1','1','1','1','1','1','1','1'])

In [62]:
from pathlib import Path  # 파일 경로!!!!! 매우 중요!!!! 리눅스도 다 알아서 해줄게
p = Path('kdt02_python/01_study/Numbers.txt')
#p = Path('kdt02_python\\Numbers.txt')
p.read_text(encoding='utf8').split()

FileNotFoundError: [Errno 2] No such file or directory: 'kdt02_python\\01_study\\Numbers.txt'

In [ ]:
from pathlib import Path  # 파일 경로!!!!! 매우 중요!!!! 리눅스도 다 알아서 해줄게
p = Path('kdt02_python/01_study/Numbers.txt')
#p = Path('kdt02_python\\Numbers.txt')
p.write_text('1\n2\n3\n4\n')

In [63]:
from pathlib import Path

p = Path('Numbers.txt')

In [ ]:
list(p.glob)

In [ ]:
with open('Numbers.txt', 'w') as f:
    f.write()

In [73]:
try:
    with open('Numbers5.txt', 'w') as f:
        f.read()
except FileNotFoundError as e:
    print('FileNotFoundErr!', e)
    print('Error!')
except Exception as e:
    print(e)
    print('Unkown Error!')

not readable
Unkown Error!

In [ ]:
try:
    raise FileNotFoundError('Hello')
except FileNotFoundError as e:
    print('FileNotFoundErr!', e)
    print('Error!')
except Exception as e:
    print(e)
    print('Unkown Error!')

FileNotFoundErr! Hello
Error!

In [77]:
def add(a, b):
    raise FileNotFoundError('hello')

def main():
    try:
        add(1,2)
    except FileNotFoundError as e:
        print('FileNotFoundErr!', e)
    except Exception as e:
        print('Unkown Error!', e)

main()

FileNotFoundErr! hello

CSV 파일

In [5]:
import csv

with open('grade.csv', 'r') as f:
    file = csv.reader(f)
    students = {}
    subjects = {}
    headers = next(file) # 첫번째 라인 날아가고 나서
    for line in file:
        #print(line)
        name, java, pyth = line[0], int(line[1]), int(line[2])
        students[name] = sum([java, pyth])/2
        subjects['java'] = subjects.get('java', 0) + java
        subjects['python'] = subjects.get('python', 0) + pyth
students

{'Kim': 85.0, 'Lee': 82.5, 'Park': 55.0}

In [100]:
# 학생별 평균

# 점수별 평균
for k, v in subjects.items():
    print(k, v/len(subjects))

java 113.5
python 109.0

In [ ]:
%pip install pandas

In [101]:
import pandas as pd

df = pd.read_csv('grade.csv')
df.head()

   name  java  python
0   Kim    90      80
1   Lee    77      88
2  Park    60      50

In [ ]:
df.sum(axis=0) # col로 합계

name      KimLeePark
java             227
python           218
dtype: object

In [126]:
df.iloc[:,:1].sum(axis=1) #

0     Kim
1     Lee
2    Park
dtype: object

In [95]:
df.describe()

            java     python
count   3.000000   3.000000
mean   75.666667  72.666667
std    15.044379  20.033306
min    60.000000  50.000000
25%    68.500000  65.000000
50%    77.000000  80.000000
75%    83.500000  84.000000
max    90.000000  88.000000

In [123]:
df.to_csv('grade2.csv')

Json

In [ ]:
import json

lst = [1,2,3]

content = json.dumps(lst) # '[1, 2, 3]' serialize
print(type(content), content)

request =json.loads(content) # [1, 2, 3] unserialize
print(type(request) ,request)

<class 'str'> [1, 2, 3]
<class 'list'> [1, 2, 3]

In [ ]:
data = {
    'Kim': [90,80],
    'Lee': [77,88],
    'Park': [60,50],
}

data2 = { # col로 
    'name': ['Kim','Lee','Park'],
    'java': [90,77,60],
    'python': [80,88,50],
}

response = json.dumps(data) # '{"Kim": [90, 80], "Lee": [77, 88], "Park": [60, 50]}'

request = json.loads(response) # {'Kim': [90, 80], 'Lee': [77, 88], 'Park': [60, 50]}
print(type(request), request)

<class 'dict'> {'Kim': [90, 80], 'Lee': [77, 88], 'Park': [60, 50]}

In [121]:
with open('data.json', 'w') as f:
    json.dump(data2, f)

with open('data.json', 'r') as f:
    data4 = json.load(f)

data

{'Kim': [90, 80], 'Lee': [77, 88], 'Park': [60, 50]}

In [122]:
#전통적 방법
import pickle

with open('data.bin', 'wb') as f:
    pickle.dump(data2, f)

with open('data.bin', 'rb') as f:
    data3 = pickle.load(f)

data3

{'name': ['Kim', 'Lee', 'Park'], 'java': [90, 77, 60], 'python': [80, 88, 50]}

In [ ]:
import csv
with open('grade.csv', 'r') as f:
    reader = csv.DictReader(f) # next()로 header 안 날려줘도 된다! 
    for row in reader:
        print(row['name']) # column이름을 키로 사용할 수 있어서 편하다!
        print(row['java'])
        print(row['python'])

Kim
90
80
Lee
77
88
Park
60
50